version: '3.9'


services:
  app:
    container_name: 'web'
    build:
      context: ./front
      dockerfile: Dockerfile

    ports:
      - '5173:5173'

    volumes:
      - ./front:/app/front
      - /app/front/node_modules

    networks:
      red_web:
        ipv4_address: 192.168.10.10
      
      red_interna:
        ipv4_address: 192.168.20.10

  backend: 
    container_name: 'api'
    build: 
      context: ./backend
      dockerfile: Dockerfile
    
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    
    ports:
      - '8000:8000'

    volumes:
      - ./backend:/app/backend

    networks:
      red_web:
        ipv4_address: 192.168.10.20
      
      red_interna:
        ipv4_address: 192.168.20.20


networks:
  red_web:
    ipam:
      config:
        - subnet: 192.168.10.0/24
  red_interna:
    ipam:
      config:
        - subnet: 192.168.20.0/24
