version: '3.9'


services:

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile

    ports:
      - '5173:5173'

    volumes:
      - ./front:/app/front

    depends_on:
      - backend

  backend: 
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'

    volumes:
      - ./backend:/app/backend